In [9]:
import numpy as np
from hmmlearn import hmm

model = hmm.GaussianHMM(n_components=3, covariance_type="diag", n_iter=100)
X = np.random.rand(100, 1)
lengths = [len(X)]
model.fit(X, lengths)
hidden_states = model.predict(X)

print("Transition matrix:\n", model.transmat_)
print("Hidden states:\n", hidden_states)


Transition matrix:
 [[4.81474052e-07 7.15512743e-01 2.84486776e-01]
 [3.03176131e-01 4.74352454e-01 2.22471415e-01]
 [2.07121177e-01 6.07268807e-01 1.85610015e-01]]
Hidden states:
 [2 0 1 1 2 1 1 1 2 1 0 1 2 1 2 1 1 1 0 1 1 0 1 0 1 2 1 2 0 2 1 1 1 0 2 1 0
 2 2 0 1 0 1 1 0 1 2 0 1 1 2 0 1 1 1 0 2 0 1 0 2 1 2 1 1 2 1 2 1 2 2 1 0 2
 1 2 1 1 0 1 0 1 0 1 1 1 0 1 0 2 1 2 2 2 1 1 1 0 1 1]


In [8]:
!pip install hmmlearn


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 4.2 MB/s eta 0:00:00
